# Generated by Django 3.0.4 on 2020-10-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
