# Generated by Django 3.0.4 on 2020-10-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userinfo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ctime',
            field=models.DateTimeField(null=True),
        ),
    ]
