# Generated by Django 3.0.4 on 2020-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_userinfo_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='Decimaler',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='color',
            field=models.IntegerField(choices=[(1, 'black'), (2, 'white'), (3, 'blue')], null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='floater',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='integer',
            field=models.IntegerField(null=True),
        ),
    ]
