# Generated by Django 3.0.4 on 2020-10-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201017_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='root@root.com', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='integer',
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
