# Generated by Django 3.0.4 on 2020-10-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='nid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='user',
        ),
    ]
