# Generated by Django 3.1.1 on 2020-10-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='usertype',
            name='fo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.foo'),
        ),
    ]
