# Generated by Django 3.0.4 on 2020-10-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_boy_girl_love'),
    ]

    operations = [
        migrations.RenameField(
            model_name='girl',
            old_name='nick',
            new_name='name',
        ),
    ]
