# Generated by Django 3.0.4 on 2020-10-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201017_1322'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='love',
            unique_together={('b', 'g')},
        ),
    ]
