# Generated by Django 3.0.4 on 2020-10-17 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201017_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='love',
        ),
    ]
