# Generated by Django 3.0.4 on 2020-10-17 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_boy_m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boy',
            name='m',
        ),
    ]
