# Generated by Django 3.0.4 on 2020-10-17 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_boy_m'),
    ]

    operations = [
        migrations.CreateModel(
            name='love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Boy')),
                ('g', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Girl')),
            ],
            options={
                'unique_together': {('b', 'g')},
            },
        ),
        migrations.AddField(
            model_name='boy',
            name='m',
            field=models.ManyToManyField(through='app.love', to='app.Girl'),
        ),
    ]
