# Generated by Django 3.0.4 on 2020-10-21 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btoy',
            name='b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='g', to='app01.UserInfo'),
        ),
        migrations.AlterField(
            model_name='btoy',
            name='g',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b', to='app01.UserInfo'),
        ),
    ]
