"""
Django settings for ep6 project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from getpass import getuser
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'sn^y8%*(+1i)uh^3za+ed9#1__)wk%f_e$p1jrh!-v9i%y!v_i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ep6.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'TEMPLATES')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ep6.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

if getuser() == 'rico':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'dj_ep6',
            'USER': 'root',
            'PASSWORD': 'rico0125',
            'HOST':'localhost',
            'PORT':'3306',
        }
    }
else:
    DATABASES ={
        'default':{
            'ENGINE':'django.db.backends.mysql', #写死的 django.db.backends.mysql
            'NAME':'dj_ep6', #DATABASE的名字
            'USER':'root',
            'PASSWORD':'0125',
            'HOST':'localhost',
            'PORT':'3306',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS =(
    os.path.join(BASE_DIR,"temp"),
)

#以下为默认值，要改哪一条单拿出来改
SESSION_COOKIE_NAME='sessionid' #控制浏览器cookie保存随机字符串的key的名字
SESSION_COOKIE_PATH='/'         #生效的url，'/'代表所有的页面都生效
SESSION_COOKIE_DOMAIN=None      #生效的域
SESSION_COOKIE_SECURE=False     #HTTPS
SESSION_COOKIE_HTTPONLY =True   #http传输
SESSION_COOKIE_AGE =1209600     #保存周期2周，这个优先级比程序中的低
SESSION_EXPIRE_AT_BROWSER_CLOSE =False   #是否关闭游览器时session过期
SESSION_SAVE_EVERY_REQUEST =False   #是否每次请求都保存session，默认修改之后才保存，若改为true 每次request都会更新失效日期，

SESSION_ENGINE ='django.contrib.sessions.backends.db'  #引擎(默认值) 放在数据库中

#小应用程序放在数据库中
#但是一般都放在缓存中

#SESSION_ENGINE ='django.contrib.sessions.backends.cache' #缓存
#SESSION_CACHE_ALIAS ='default'
#缓存 相当于另一台机器的内存中，另一台机器叫缓存服务器
#配合django的缓存配置

#SESSION_ENGINE ='django.contrib.sessions.backends.cached_db' #缓存+数据库
#优先在缓存里面找，没有的时候去数据库里找



#SESSION_ENGINE ='django.contrib.sessions.backends.file' 放在文件里
#SESSION_FILE_PATH =None 若路径为none 则使用tempfile模块获取临时地址tempfile.gettempdir()

#SESSION_ENGINE ='django.contrib.sessions.backends.signed_cookies' 放在里cookie里 相当于没用session 这个不推荐


